"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _profile_update_form from './profile-update-form.bones.json'

registerBones({
  "profile-update-form": _profile_update_form,
})
